### ISSUE TITLE
Unhandled rejection Error 401

### ISSUE THREAD

**Issue by hyprem** [onedr0p/telegram-couchpotato-bot#19]
Not sure but the config and acl file gets loaded correctly...
`Unhandled rejection Error: Error: 401 {"ok":false,"error_code":401,"description":"[Error]: Unauthorized"}
    at /Applications/telegram-couchpotato-bot/couchpotato.js:44:11
    at tryCatcher (/Applications/telegram-couchpotato-bot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/telegram-couchpotato-bot/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Applications/telegram-couchpotato-bot/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Applications/telegram-couchpotato-bot/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Applications/telegram-couchpotato-bot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/telegram-couchpotato-bot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/telegram-couchpotato-bot/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by onedr0p** [comment]
`Error: 401 {"ok":false,"error_code":401,"description":"[Error]: Unauthorized"}` this is a message from the Telegram server.

This maybe because of an incorrect telegram bot ID please verify the ID is correct and/or regenerate it.

**Comment by hyprem** [comment]
hmm would be great to get a status to see if error comes from telegram or the script it self but true it was the wrong token

**Comment by onedr0p** [comment]
A 401 message could be different problems, take a look at their error page under 401:

https://core.telegram.org/api/errors
