### ISSUE TITLE
Changes seem to have broken this

### ISSUE THREAD

**Issue by ghost** [onedr0p/telegram-couchpotato-bot#34]
i think telegram changes made today or last night seem to have broken this from working. havent changed anything since install sometime last year and the bot can't talk now. gets everything but throws errors on response. i know the original author isn't involved anymore. just wondering if anyone else is getting what i am getting to know if its just me or all. have fresh installed on a seperate machine with a new seperate bot and i get the same errors.

**Comment by felixbouleau** [comment]
I'm having the same problem:

```
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}
    at /app/node_modules/node-telegram-bot-api/src/telegram.js:111:15
    at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:384:17)```

**Comment by pantar85** [comment]
same error here. ah well. was good while it lasted.

**Comment by onedr0p** [comment]
Telegram most likely made API changes that broke the bot. I don't use telegram or couchpotato, but I will still accept PRs if anyone is interested in contributing.

**Comment by xoniq** [comment]
Seems to be a temporary thing. Mine wasn't working too, but tonight I tried again, and suddenly it responded again. Can be closed.

**Comment by pantar85** [comment]
its responding now but every query besides /help results in

`Oh no! Error: getaddrinfo ENOTFOUND media media:5050`

**Comment by dolohow** [comment]
Is this still an issue?  I am using this bot till this date and it is working fine.

**Comment by RPWouters** [comment]
Same problem here running on my NetGear NAS. Don't have the problem when I run it on my PC.
